project_id = "hzlinabncewcahdnobet"

[functions.purchase-credits]
verify_jwt = false

[functions.spend-credits]
verify_jwt = false

[functions.generate-spoc-qr]
verify_jwt = false

[functions.validate-spoc-qr]
verify_jwt = false

[functions.reset-device]
verify_jwt = false

[functions.stability-pool-contribute]
verify_jwt = false

[functions.videosdk-token]
verify_jwt = false

[functions.ai-transcribe]
verify_jwt = false

[functions.ai-moderate]
verify_jwt = false

[functions.create-bulk-temp-ids]
verify_jwt = false

[functions.verify-temp-credentials]
verify_jwt = false

[functions.activate-account]
verify_jwt = false
